### ISSUE TITLE
`ReferenceQueue` support

### ISSUE THREAD

**Issue by rschmitt** [platypusguy/jacobin#65]
I was curious to know how Jacobin would support features like `ReferenceQueue<T>` and `WeakReference<T>` through the Go garbage collector. I had ChatGPT generate a quick demo program:

```java
import java.lang.ref.ReferenceQueue;
import java.lang.ref.WeakReference;

public class ReferenceQueueDemo {

    public static void main(String[] args) throws InterruptedException {
        // Create an object
        Object obj = new Object();

        // Create a reference queue
        ReferenceQueue<Object> refQueue = new ReferenceQueue<>();

        // Create a weak reference to the object with the reference queue
        WeakReference<Object> weakRef = new WeakReference<>(obj, refQueue);

        // Initially, the reference queue should be empty
        System.out.println("Reference queue poll: " + refQueue.poll());

        // Nullify the strong reference to the object
        obj = null;

        // Suggest garbage collection
        System.gc();

        // Wait for a moment
        Thread.sleep(1000);

        // Check if the weak reference has been enqueued
        if (refQueue.poll() == weakRef) {
            System.out.println("The weak reference was enqueued, meaning the object was garbage collected.");
        } else {
            System.out.println("The object was not garbage collected.");
        }
    }
}
```

Seems to work in Corretto 17:

```
C:\src\jacobin\src> java ReferenceQueueDemo
Reference queue poll: null
The weak reference was enqueued, meaning the object was garbage collected.
```

Jacobin just crashes:

```
C:\src\jacobin\src> jacobin.exe ReferenceQueueDemo.class
LoadClassFromNameOnly: null class name is invalid
goroutine 1 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        C:/Program Files/Go/src/runtime/debug/stack.go:16 +0x13
jacobin/classloader.LoadClassFromNameOnly({0x0, 0x0})
        C:/src/jacobin/src/classloader/classloader.go:290 +0x545
jacobin/jvm.loadThisClass({0x0, 0x0})
        C:/src/jacobin/src/jvm/instantiate.go:310 +0x45
jacobin/jvm.instantiateClass({0xc003a84500, 0x10})
        C:/src/jacobin/src/jvm/instantiate.go:65 +0x325
jacobin/jvm.runFrame(0xc003753920)
        C:/src/jacobin/src/jvm/run.go:1882 +0x885a
jacobin/jvm.runThread(0x2fdd80)
        C:/src/jacobin/src/jvm/run.go:92 +0x2b
jacobin/jvm.StartExec({0xc0046f30b0, 0x12}, 0x2fe260)
        C:/src/jacobin/src/jvm/run.go:82 +0x6bc
jacobin/jvm.JVMrun()
        C:/src/jacobin/src/jvm/jvmStart.go:94 +0x44f
main.main()
        C:/src/jacobin/src/main.go:12 +0xf
instantiateClass: Failed to load class
LoadClassFromNameOnly: null class name is invalid
```

**Comment by platypusguy** [comment]
Ryan: Thanks for this report! In the Releases section of this site, we stress that Jacobin is not ready for use or even testing. However, we will take your code, which I really appreciate, and put it in our test suite as part of our validation. Whenever your test passes, I'll reopen this issue and update it with that result. Again, thank you!
